spring.application.name=siconbol
spring.datasource.url=jdbc:mysql://localhost:3306/proyect_siconbol?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.main.banner-mode=off

#Para ver más detalles en los logs de Spring Boot
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG


#Habilitar api docs y swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# /swagger custom path
springdoc.swagger-ui.path=/doc/swagger-ui.html
# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs